### PR TITLE
Created a bash script for generating icons

### PR DESCRIPTION
**Pull request by markus-li**
This bash script can be used to generate icons in all the required resolutions. It has been tested on Debian and has a comment on what the dependencies there are.
It's just a simple utility script, but since the existing one is meant for Windows only I thought this could be useful.

### CODE REVIEW

**Comment by markus-li** [comment]
@DustinBrett btw, if you want to chat about any of these pull-requests outside of comments, look me up on http://community.oh-lalabs.com user markus and we could chat on eg. Signal. I'd be happy to provide any additional feedback you may want.

**Comment by DustinBrett** [comment]
This is quite interesting. Thanks for this. I will do some testing and think on the tools being used and if the way I am doing it with my batch file is even ideal. I know my batch file is not ideal as it's quite WET and I would like to get into finer detail with the flags as I am trying for a loseless image. A step not shown in my batch file is that I run this through https://nikkhokkho.sourceforge.io/static.php?page=FileOptimizer on Windows which I have found does a great job of squeezing a little more out of these images.

**Comment by markus-li** [comment]
FileOptimizer is using a bunch of external dependencies, which for webp and png optimization probably exist as stand-alone utils/libraries both for Windows and Linux. Once you've decided on a set of tools and parameters, I'd be happy to adjust this script so that the results are the same on Linux.

**Comment by DustinBrett** [comment]
Thanks for this script but I think just the one is ok for now as I don't expect people to run it or have the tools, its more like a doc to show what I did to make the images on my site, but its not required for anyone and users can make images however they want and follow the format based on the script and existing icons.

**Pull request closed without merging**
