### PR TITLE
Support for a split public folder

### PR DESCRIPTION
**Pull request by markus-li**
This is my suggestion on how to make the "public/" folder fully customizable without having to risk merging conflicts. 
Build like normal with "yarn build" or "yarn build:prebuild" or for skipping "publicDefault/" "yarn build:minimal" or "yarn build:prebuild:minimal".
To add files/folders which don't belong in the main repo, just put them in "publicCustom/". Since that fodler is always kept empty/missing in the main repo it is easy to merge with.

### CODE REVIEW

**Comment by markus-li** [comment]
The issues are the same as those which existed before moving the files in "public/" to "publicMinimal/" and "publicDefault/". None of the files in those locations have been modified in any way, except for the fact they have been moved.

**Comment by DustinBrett** [comment]
Thanks for this PR as well. I will check this out and think on how best to make daedalOS more customizable in this way. I'm not sure if it would be exactly this way as `public` pulls double duty in a few areas possibly, but I need to understand the customization gaps I have now to see where this fits in.

**Comment by markus-li** [comment]
Since there can only be one public folder with next, this would give maximum flexibility to change things in my opinion. It also provides a simple way to split the base public folder into a minimal and default one. Looking forward to what you will do with this, it is a type of feature I think will be very good to have, however it may be implemented.

**Comment by DustinBrett** [comment]
Thank you for this PR. I will think on the idea of making customization more clear, but at the moment I actually feel like public is very customizable, even if it will break apps, it's like when you install Windows and can do anything to `C:\`, even if it breaks stuff. So I prefer to have 1 `public` folder at the moment and allow any forks to edit this folder directly as if it's `C:\`.

**Comment by markus-li** [comment]
While I can understand your reasoning I'm still hoping you will change your mind on this. Taking your analogy of how c:\ works I'd say that if public was split to Minimal and Default it would allow to "install" the "software" to C:\ and then build on that with whichever additional pieces one would want. 
As a way to convey my very strong wishes for a modularized App model now, rather than later, I created a sample branch [https://github.com/markus-li/daedalOS/tree/apps](https://github.com/markus-li/daedalOS/tree/apps). To be complete this self-contained app model would require public to be split. An app could be maintained in a separate repo and just included as a submodule into the components/app folder. As an example I have moved out BoxedWine and made it into a self-contained app. During a normal build all apps as defined in "appsEnabledDefaults" are included. To enable custom Apps they just need to be uncommented in the non-version-controlled file "appsEnabled". All 100% self-contained.
The part in the app which is in "components/apps/BoxedWine/public" is not currently automatically included in "public", but would be in a full version of doing this, same way as it is done in this PR regarding a split public folder.
It may not be ideal, but nothing says that you can't evolve the model, even with breaking changes. As it is now, many changes are "breaking" in terms of keeping "3rd party" apps working flawlessly. I do have an app or two I'd love to put in a repo which could be included as a submodule in git.

**Pull request closed without merging**
