### PR TITLE
Moved StartButtonIcon into the theme.

### PR DESCRIPTION
**Pull request by markus-li**
This pull-request is one in a series I plan to do if there's interest. The goal is to make it easier to customize daedalOS. This first pull request only moves StartButtonIcon into the theme, providing a way to define it on a per-theme basis.
If this pull-request is approved I'll make the next one soon.

### CODE REVIEW

**Comment by DustinBrett** [comment]
Thanks for this PR. I like the idea of theme icons. I'd like to think on this idea and perhaps move others and make an `icons` import to go with the other generic imports like `colors` and `sizes`.

As for overrides I think in most cases I would rather it pull from only 1 place and the default be overridable by a theme or some kind of configuration in 1 place.

And as for eslint ignores, those are to be avoided at all costs as well as most TODO's or placeholder code.

I will indeed run with these ideas as I find the idea of moving the theme and anything customizable up as high as possible to allow further customization.

**Comment by markus-li** [comment]
Sorry about that, that second commit was never supposed to be part of this since it is very much not ready. It was supposed to be only the one about the StartButtonIcon.
I have another pull request I'll push regarding mergeable public folders which enables customization to be done fairly easily. Maybe it is something which may be to your liking, but if not at least it may give you some ideas. I'm really hoping you'll get code in which will make it easier to keep a customized version of daedalOS around.

**Comment by DustinBrett** [comment]
Thanks for this PR. I like the idea of the icons in the theme and when I eventually make a 2nd theme, I will keep this in mind as I have a larger plan for how customization will work going forward. At the moment I would rather not integrate this as I have a larger plan for theming. Ideally I hope in the future for users to be able to theme and add apps without needing to touch the code or configs, and instead bringing in bundles that can integrate with the process directory and theming.

If down the road I did add this, 2 adjustments I would make would be to destruct the icon from `theme` so L50 can remain as is, `const { StartButtonIcon } = useTheme();` and instead of adding `StartButtonIcon` directly to the theme, I would add `icons: typeof icons;` and within the `icons` file I would have various icons such as the start button and possib ly every basic SVG I use at the system level.

**Comment by markus-li** [comment]
Hope this can be done sooner rather than later then :)

**Pull request closed without merging**
