### PR TITLE
Added dockerfile with basic usage information

### PR DESCRIPTION
**Pull request by ProtocolNebula**
Added dockerfile with instructions in it

Because I dont want to break the Readme.md, I prefer to write the instructions in that file.

In the future, if no one do it, I'll improve it and also publish/autopublish to Docker repository if is not done in the main repo.

## Dockerfile to start a docker in DEV mode

1. To generate the docker:
```bash
docker build -t daedalos:v1 .
```

2. To run the docker:
```bash
docker run -d --rm -p 3000:3000 --name daedalos daedalos:v1
```

## Docker Compose example

```yaml
version: '3'
services:
  daedalos:
    container_name: daedalos
    image: "daedalos:v1"
    # volumes:
    #   - /path/to/folder/host:/folder/in/docker
    restart: unless-stopped
    privileged: true
    networks:
      - daedalos
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.daedalos.rule=Host(`os.nas.racs.es`)"
      - "traefik.http.routers.daedalos.entrypoints=websecure"
      - "traefik.http.services.daedalos.loadbalancer.server.port=3000"
      - traefik.http.routers.daedalos.tls=true
      - traefik.http.routers.daedalos.tls.certresolver=letsncrypt

networks:
  daedalos:
    name: racsdocker
```

### Run docker compose:

```bash
docker-compose up -d
# STOP:
# docker-compose down -d
```

### CODE REVIEW

**Comment by DustinBrett** [comment]
I am actually working on a similar file right now as it's been requested by a few people. I will try this file out this week. Thanks!

**Comment by ProtocolNebula** [comment]
There's no issue, I just want to help, will be or not my commit in the repo haha.
In fact, I created that docker because I needed it to deploy without too effort in my NAS.

I hope it helps you :)

**Comment by DustinBrett** [comment]
Thanks again for this. I have gone ahead and done some tweaks and committed a Dockerfile. I'll leave this PR open for now incase you have any comments on the commit I ended up doing.

https://github.com/DustinBrett/daedalOS/commit/2acdb09bae6409e49767b7eaf0375d75171d21f1

**Comment by ProtocolNebula** [comment]
I guess that your MR is better than this, you can close this MR.
I'm glad to have an official dockerfile for this!

**Pull request closed without merging**
