### PR TITLE
Adding a few more commands for the github client

### PR DESCRIPTION
**Pull request by alanboy**
This adds the ability to git add files, create commits, and push commits to the remote repo. `git status` also works.

I was very interested in making git as close as possible to an actual git client but now I'm exploring the linux route to be able to have a fully functional git terminal in dadedalOS, so I paused this work. Since I did get some features working I figured I would share this PR as a starting point.

Notes:
* The git user is John Doe since I don't have any reference to the user and git cofig is not implemented.
* There is no auth. Only works on public repos.
* Ignore the docker compose.

### CODE REVIEW

**Comment by DustinBrett** [comment]
Thanks for these additions. I'll look through this code and adapt it asap.

**Comment by DustinBrett** [comment]
How would `push` work if you aren't logged in? How can I test these commands?

**Comment by DustinBrett** [comment]
@alanboy Could I get some steps to reproduce/test these new features? Do you have an example repo? I am not clear how you could push anything without logging in.

**Comment by DustinBrett** [comment]
So I've taken the time to add (https://github.com/DustinBrett/daedalOS/commit/c5701d7e06b5584d6dbf90699d03b8e565d1b3a7) isogit cli (https://isomorphic-git.org/docs/en/cli) support into Terminal. Now it basically supports the cli to the same level that npm's `isogit` itself does. I used their code (https://github.com/isomorphic-git/isomorphic-git/blob/main/cli.cjs) as an example which also uses https://github.com/minimistjs/minimist to parse `--` parameters into an options object.

I've updated help with the 14 commands worth mentioning, but it will work with any isomorphic-git command (https://isomorphic-git.org/docs/en/alphabetic). One current limitation is it can't do objects like `headers`.

For authentication during operations like push or clone I have allowed `username` and/or `password` to be passed, as is done in the example for `push` (https://isomorphic-git.org/docs/en/push) which uses `onAuth` and assumes that `username` is `GITHUB_TOKEN`.

I am going to close this PR as I prefer the less code / generalized solution that emulates what isomorphic-git themselves are doing for cli interfacing. I will consider specific logic on a per command basis, as I have done for `clone` to change `dir`.

**Comment by alanboy** [comment]
Hey @DustinBrett, sorry for the delay. I was out on vacation, I did the ol' push code and go on vacation stunt. I run my own git servers that don't require auth, so it was not an issue for me. I agree less code/general solution is better! Thanks for adding this.

**Pull request closed without merging**
